### ISSUE TITLE
A possible ambiguity in Section 3.5 Exercise 6 

### ISSUE THREAD

**Issue by appomsk** [osj1961/giam#15]
I counted nine 4-digit vampire numbers because of the word "union". I thought about the set operation, and then `set('5775') = set('75') & set('77')` (Python code). So with 8918 = 91*98.

My bad English is the main cause, of course :). But I think other people can confuse too.
 
Thank you for your work.

**Comment by osj1961** [comment]
The word "union" was indeed misleading.  What's really desired is "union as a multiset" but that concept comes much later.  Changed the phrasing to "v contains precisely the digits of x and y in some order."
