### ISSUE TITLE
Possible mistake in the truth table at 2.2 Implication

### ISSUE THREAD

**Issue by visrosa** [osj1961/giam#22]
It seems the truth table for A⟺B has the wrong value on the third row. It's exactly the same as the truth table for A⟹B earlier in the text.

I would have sent a PR but I'm just a student who is not sure whether there's really a mistake here. I'd be glad to fix it and send a PR if requested, though.

**Comment by osj1961** [comment]
I think you're mistaken, the A⟹B truth values go True,False,True,True as one reads down through the rows.  For A⟺B 
it is True, False, False, True
